export const UPDATE_LAST_XCORD = "UPDATE_LAST_XCORD ";
export const UPDATE_LAST_YCORD = "UPDATE_LAST_YCORD ";
export const UPDATE_PCT = "UPDATE_PCT";
export const UPDATE_ZOOM_VALUE = "UPDATE_ZOOM_VALUE";
